---
title: "Systematic Exploration of Single-Cell Morphological Phenotypes Associated with a Transcriptomic Query"
author: "Isar Nassiri, Matthew McCall"
date: "June 12, 2017"

output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Systematic Exploration of Single-Cell Morphological Phenotypes from Transcriptomic Profile\}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## 1. Introduction

Single-cell morphological phenotypes, including shape, size, intensity, and texture of cellular compartments have been shown to change in response to perturbations. Image-based morphological profiling has been used to associate phenotypic changes with alterations in cellular function and to infer molecular mechanisms of action. Recently, the Library of Integrated Network-based Cellular Signatures (LINCS) Project has measured gene expression and performed morphological profiling on 9,515 unique drug/cell-line combinations. This data provide an opportunity to study the interdependence between transcription and cell morphology. Previous methods to investigate cell phenotypes have focused on targeting candidate genes as components of known pathways, RNAi morphological profiling, and cataloging morphological defects; however, these methods do not provide an explicit model to link transcriptomic changes with corresponding alterations in morphology. To address this, we propose a cell morphology enrichment analysis to assess the association between transcriptomic alterations and changes in cell morphology. In our approach we: (1) map a query profile of transcriptomic alterations against the LINCS repository, (2) create query specific gene sets for cell morphological features (CM), (3) identify the top CMs associated with the query, and (4) model a regulatory network associated with an enriched morphological phenotype. For a new transcriptomic query, our approach can be used to predict associated changes in cellular morphology. We demonstrate the utility of our pipeline by applying it to expression changes in human bone osteosarcoma cells. The pipeline is implemented as an R package, called CMEA (acronym of the cell Morphological Enrichment Analysis).

## 2. Input data
We demonstrate the application of the CMEA package by using the transcriptomic and single cell morphological profiles of human bone osteosarcoma cells (U-2 OS cells) in response to the 9515 drugs or small molecule compounds (1). The raw data include the transcripotimic profiles of 20340 drugs and small compound molecules, and single cell morpohological profiles of 19864 drugs and small compound molecules. These data sets were published in 2014  and are available as supplementary files of (2). We used a processed version of this data, which is available as supplementary of (3). The intersection of transcriptomic and single-cell morphological profiles includes 9515 drugs and small compound molecules, and use as a backend repository of CMEA package. 
The transcriptomic profile in backend repository is 9515*978 matric, including the fold change of the 978 landmark gene expression in response to the treatment of U-2 OS cells with 9515 drugs and small compound molecules. 

```{}
head(Transcriptomic_Profile)[1:5]
                   PSME1       ATF1        RHEB      FOXO3        RHOA
BRD-A06352508 -1.0118604  2.0126676  0.24396738 -0.7628808 -0.50666198
BRD-A09925278  2.2572466  0.2357585 -0.87237056  0.4297276 -0.87052867
BRD-A11678676  0.4488044  0.3092559 -0.36787168  1.8814198  0.42195614
BRD-A17065207 -0.6854848  0.1017337 -0.54498299  0.4173902 -1.32915231
BRD-A18763547 -1.3863898 -0.3133108 -0.04048412  2.3872502 -0.07457028
BRD-A26384407  3.0705105  0.7718576 -0.15855832 -0.1994762 -0.12763418
```

The single-cell morphological profile in backend repository is 9515*812 matric, including the fold change of 812 cell morphological features in response to the treatment of U-2 OS cells with 9515 drugs and small compund molecules.

```{}
head(Cell_Morphology_Profile)[1:3]
              Cells_AreaShape_Area Cells_AreaShape_Compactness Cells_AreaShape_Eccentricity
BRD-A06352508           0.07349663                   5.3698176                    4.8470624
BRD-A09925278          -0.09968748                  -0.3722763                   -1.0475846
BRD-A11678676           0.69289901                   0.3576256                    1.3708629
BRD-A17065207          -3.53088126                   1.7724848                    1.5016300
BRD-A18763547          -0.09247960                   0.2351752                   -0.1964067
BRD-A26384407          -0.24611441                   0.3526544                    0.1375016
```

The complete data set, including raw and processed data, is available at (https://isarnassiri@bitbucket.org/isarnassiri/cmeadata).

## 3. Mapping query transcriptomic profile against the reference repository

We use the Mapping() function to map the query profile (Q) of fold change of gene expression versus reference repository of transcriptomic data (T) and detect similar profiles (s). 

Example of application: identification of similar drugs with the transcription profile of "BRD-K37798499":
```{}
Mapping("BRD-K37798499") #"BRD-K37798499" is a query.
```

You can find the results in your current directory.

## 4. Cell morphology enrichment analysis

For cell morphology enrichment analysis, we use the CellMorphologyEnrichmentAnalysis() function for variable selection and fit a sparse model based on the strong 
correlation between the transcription and single-cell morphological profiles. We present the results of the cell morphology enrichment analysis as cross-tabulation of 
landmark genes, and single-cell morphological features including the direction of effects (up or down regulation). 

Example of application:
```{}
CellMorphologyEnrichmentAnalysis(20, "BRD-K37798499") #10 is the number of first top cell morphological features.
crossTabulation(10, 20, "BRD-K37798499")              #10 is the number of first top cell morphological features, and "BRD-K37798499" is a query.
```

You can find the results in your current directory.

## 5. Rank Cell Morphological Features

We use the RankCellMorphologicalFeatures() function to consider the connectivity and centrality of features in Cosine similarity network of image-based cell morphological profile to rank cell morphological features. We present the first top N cell morphological features, ranked based on the Strength Centrality Score (SCS) in a questionnaire graph.
   
Example of application:
   
```{}
RankCellMorphologicalFeatures(20, 20, "BRD-K37798499") #10 is the number of first top cell morphological features, and "BRD-K37798499" is a query.
```
You can find the results in your current directory.

## 6. Association rule mining of transcriptomic and cell morphological profiles

We use an association mining model to detect the associations between the genes and to infer a gene regulatory network from phenotypic experimental data. To infer a gene regulatory network for a cell morphological phenotype, first, we mine association rules between genes based on the cell morphological gene sets (Section 3). Next, we apply the Context Likelihood (CLR) network inference algorithm to identify the interactions between genes based on the transcriptomic profiles (Ts,978). CLR infers the interactions between genes by using a scoring function based on the empirical distribution of mutual information. We select interactions are shared between the association rules and CLR to represent a cell morphological phenotype gene regulatory network (GRN).

Example of application:
```{}
GRN(10, 0.1, 0.6, "BRD-K37798499") 
```
You can find the results in your current directory.

## References:
1. Lamb, J., Crawford, E.D., Peck, D., Modell, J.W., Blat, I.C., Wrobel, M.J., Lerner, J., Brunet, J.P., Subramanian, A., Ross, K.N. et al. (2006) The connectivity map: Using gene-expression signatures to connect small molecules, genes, and disease. Science, 313, 1929-1935.
2. Wawer, M.J., Jaramillo, D.E., Dancik, V., Fass, D.M., Haggarty, S.J.,
Shamji, A.F., Wagner, B.K., Schreiber, S.L. and Clemons, P.A. (2014)
Automated Structure-Activity Relationship Mining: Connecting Chemical
Structure to Biological Profiles. Journal of Biomolecular Screening, 19,
738-748.
3. Wang, Z., Clark, N.R. and Ma'ayan, A. (2016) Drug-induced adverse events prediction with the LINCS L1000 data. Bioinformatics, 32, 2338-2345.
